spring.application.name=GmailSender
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=zillagoji8@gmail.com
spring.mail.password=utbj utaz widf odsc

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.transport.protocol=smtp
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com