spring.application.name=MovieBookingApp
jwt.secret=gEznVx5sHVYrJQxXOYzE58853CkMnPxisGZOFTGKsa1
jwt.expiration=864000

spring.datasource.url=jdbc:postgresql://localhost:5432/movie
spring.datasource.username=postgres
spring.datasource.password=yuvi2006

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true